### ISSUE TITLE
Relationship Endpoint: Items

### ISSUE THREAD

**Issue by JerrelMitchell** [JerrelMitchell/rales_engine#17]
Items
-[x] GET /api/v1/items/:id/invoice_items returns a collection of associated invoice items
-[x] GET /api/v1/items/:id/merchant returns the associated merchant

**Comment by manojpanta** [comment]
We have one failing test for this relationships, getting 24 instead of 8.

**Comment by manojpanta** [comment]
Rest Should be done.

**Comment by manojpanta** [comment]
Looks like our connection between invoiceitems to item and invoice is not working well. thats why i have one failing test for invoices relationship.
